{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devopsapi.serviceAccountName" . }}
  labels:
    {{- include "devopsapi.labels" . | nindent 4 }}
{{- end }}
