apiVersion: v1
kind: Service
metadata:
  name: {{ include "devopsapi.fullname" . }}
  labels:
    {{- include "devopsapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "devopsapi.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
