replicaCount: 1

image:
  repository: ilya4rh/devopsapi
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

serviceAccount:
  create: false
  name: ""

resources: {}
